### ISSUE TITLE
flat array input produces all NaN results

### ISSUE THREAD

**Issue by kevzettler** [wwwtyro/geo-center#1]
```
> console.log(center([1,2,3,4,5,6], {center: [0,0,0]}))
[ NaN, NaN, NaN, NaN, NaN, NaN ]
undefined
```

**Comment by wwwtyro** [comment]
@kevzettler Thanks! [This commit](https://github.com/wwwtyro/geo-center/commit/56f6a7948c515e85721ab04c7898e6714b6d80dd) should patch it up. Published as 1.0.2.
